name: lamappgdsc
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  cloud_firestore: ^4.13.1
  cloud_firestore_platform_interface: ^6.0.5
  cloud_firestore_web: ^3.8.5
  dropdown_button2: ^2.3.9
  file_picker: ^6.1.1
  firebase_auth: ^4.14.0
  firebase_auth_platform_interface: ^7.0.4
  firebase_auth_web: ^5.8.7
  firebase_core: ^2.22.0
  firebase_core_platform_interface: ^5.0.0
  firebase_core_web: ^2.8.1
  firebase_performance: ^0.9.3+4
  firebase_performance_platform_interface: ^0.1.4+12
  firebase_performance_web: ^0.1.4+12
  firebase_storage: ^11.5.1
  flutter:
    sdk: flutter
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_plugin_android_lifecycle: 2.0.9
  flutter_spinkit: ^5.2.0
  flutterflow_ui: ^0.2.0+1
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: ^12.1.1
  google_fonts: 4.0.3
  google_sign_in: ^6.1.6
  google_sign_in_android: ^6.1.20
  google_sign_in_ios: ^5.6.5
  google_sign_in_platform_interface: ^2.4.2
  google_sign_in_web: ^0.12.1
  image_picker: 1.0.4
  image_picker_android: ^0.8.8+2
  image_picker_for_web: 3.0.1
  image_picker_ios: ^0.8.8+4
  image_picker_platform_interface: 2.9.1
  intl: 0.18.1
  json_path: ^0.6.3
  mime_type: 1.0.0
  page_transition: 2.0.4
  path_provider: ^2.1.1
  path_provider_android: ^2.2.1
  path_provider_foundation: ^2.3.1
  path_provider_platform_interface: ^2.1.1
  plugin_platform_interface: ^2.1.7
  provider: 6.0.4
  rxdart: 0.27.7
  shared_preferences: ^2.2.2
  shared_preferences_android: ^2.2.1
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: ^2.3.1
  shared_preferences_web: ^2.2.1
  sign_in_with_apple: ^5.0.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  sqflite: 2.2.6
  stream_transform: 2.1.0
  timeago: 3.2.2
  url_launcher: ^6.2.1
  url_launcher_android: ^6.2.0
  url_launcher_ios: ^6.2.1
  url_launcher_platform_interface: ^2.2.0
  video_player: ^2.8.1
  video_player_android: ^2.4.10
  video_player_avfoundation: ^2.5.2
  video_player_platform_interface: ^6.2.1
  video_player_web: ^2.1.2

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter
  image: ^4.1.3
  lints: 3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
